#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Bagtyyar.Resource", IsApplication=true)]

namespace Bagtyyar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int About_Button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int About_Button_Highlight = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int About_Button_Selected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int AboutButton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int EN = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int EN_press = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int EN_sel = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int EnButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Home_Button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Home_Button_Highlight = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Home_Button_Selected = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int HomeButton = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Restaurant_Button = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Restaurant_Button_Highlight = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Restaurant_Button_Selected = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int RestaurantButton = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Room_Service_Button = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Room_Service_Button_Highlight = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Room_Service_Button_Selected = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int RoomServiceButton = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int RU = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int RU_press = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int RU_sel = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int RuButton = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int SplashBackground = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int TileBackground = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int TM = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int TM_press = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int TM_sel = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int TmButton = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int TV_Button = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int TV_Button_Highlight = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int TV_Button_Selected = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int TVButton = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Video_Button = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Video_Button_Highlight = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Video_Button_Selected = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int VideoButton = 2130837542;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int button1 = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int buttonEN = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int buttonRU = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int buttonTM = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int imageViewSplash = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout1 = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int textViewEN = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int textViewRU = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int textViewTM = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int EntertainmentPageLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int HomePageLayout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int LanguagesLayout = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int MainLayout = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int RestaurantDetailsPageLayout = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int RestaurantPageLayout = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ServicesPageLayout = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int SplashLayout = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int TVPageLayout = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int VideoPageLayout = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
